[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.3"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
